In [1]:
import numpy as np
import matplotlib.pyplot as plt
from moc.metrics.distribution_metrics import pce
import torch
from torch.distributions import MultivariateNormal

In [2]:
torch.manual_seed(42)

In [3]:
def build_multivariate_normal(d, sigma2, tau, mean):
    indices = torch.arange(d).unsqueeze(0)
    covariance_matrix = sigma2 * torch.exp(-torch.abs(indices.T - indices) / tau)
    return MultivariateNormal(mean, covariance_matrix)

In [4]:
d = 10
sigma2 = 1.0
tau = 1.0

mean = torch.zeros(d)
true_dist = build_multivariate_normal(d, sigma2, tau, mean)
# undercorr = build_multivariate_normal(d, sigma2, tau, mean)

In [5]:
undermean = torch.ones(d) * - 0.5
undermean_dist = build_multivariate_normal(d, sigma2, tau, undermean)
overcorr_dist = build_multivariate_normal(d, sigma2, 2, mean)
undervar_dist = build_multivariate_normal(d, 0.85, tau, mean)

In [6]:
N = 10000
y = true_dist.sample((N,))
y.shape

torch.Size([10000, 10])

In [ ]:
pces, var = pce(undervar_dist, y, n_samples = 20, mode = 'all', prerank = 'mean', setup='simulated')

tensor([0.0288, 0.0000, 0.0000, 0.0306, 0.0000, 0.0337, 0.0000, 0.0000, 0.0341,
        0.0000, 0.0365, 0.0000, 0.0000, 0.0356, 0.0000, 0.0377, 0.0000, 0.0000,
        0.0380, 0.0000, 0.0404, 0.0000, 0.0000, 0.0364, 0.0000, 0.0447, 0.0000,
        0.0436, 0.0000, 0.0000, 0.0444, 0.0000, 0.0467, 0.0000, 0.0000, 0.0544,
        0.0000, 0.0538, 0.0000, 0.0000, 0.0566, 0.0000, 0.0658, 0.0000, 0.0000,
        0.0635, 0.0000, 0.0791, 0.0000, 0.0956])
average
tensor([0.0088, 0.0200, 0.0200, 0.0106, 0.0200, 0.0137, 0.0200, 0.0200, 0.0141,
        0.0200, 0.0165, 0.0200, 0.0200, 0.0156, 0.0200, 0.0177, 0.0200, 0.0200,
        0.0180, 0.0200, 0.0204, 0.0200, 0.0200, 0.0164, 0.0200, 0.0247, 0.0200,
        0.0236, 0.0200, 0.0200, 0.0244, 0.0200, 0.0267, 0.0200, 0.0200, 0.0344,
        0.0200, 0.0338, 0.0200, 0.0200, 0.0366, 0.0200, 0.0458, 0.0200, 0.0200,
        0.0435, 0.0200, 0.0591, 0.0200, 0.0756])


In [8]:
pces

[0.023200001567602158]

In [9]:
var

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.sum(pces*var)

TypeError: only integer tensors of a single element can be converted to an index